# Basic Fantasy RPG Dungeoneer Suite
# Copyright 2007-2016 Chris Gonnerman
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# Redistributions of source code must retain the above copyright
# notice, self list of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright
# notice, self list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# Neither the name of the author nor the names of any contributors
# may be used to endorse or promote products derived from self software
# without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

monsters = {
    "Basilisk": {
        "name": "Basilisk",
        "ac": 16,
        "daggers": 0,
        "asterisk": 0,
        "hd": (6, 8, 0),
        "noatt": "1 bite/1 gaze",
        "dam": "1d10/petrification",
        "mv": "20' (10')",
        "noapp": (1, 6, 0),
        "sv": "F6",
        "ml": 9,
        "tt": "F",
        "dungeonlevel": 6),
    },
    "Bear, Cave": {
        "name": "Bear, Cave",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (7, 8, 0),
        "noatt": "2 claws/1 bite + hug",
        "dam": "1d8/1d8/2d6 + 2d8 hug",
        "mv": "40'",
        "noapp": (1, 2, 0),
        "sv": "F7",
        "ml": 9,
        "tt": "None",
        "dungeonlevel": 4),
    },
    "Black Pudding": {
        "name": "Black Pudding",
        "asterisk": 1,
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (10, 8, 0),
        "noatt": "1",
        "dam": "3d8",
        "mv": "20'",
        "noapp": (0, 0, 1),
        "sv": "F10",
        "ml": 12,
        "tt": "None",
        "dungeonlevel": (6, 8)),
    },
    "Bugbear": {
        "name": "Bugbear",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 2),
        "noatt": "1 weapon",
        "dam": "1d8 or by weapon",
        "mv": "30'",
        "noapp": (2, 4, 0),
        "sv": "F2",
        "ml": 9,
        "tt": ("B", "L", "M"),
        "dungeonlevel": 3),
    },
    "Caecilia, Giant": {
        "name": "Caecilia, Giant",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (6, 8, 0),
        "noatt": "1 bite + swallow on 19/20",
        "dam": "1d8 + 1d8/round if swallowed",
        "mv": "20' (10')",
        "noapp": (1, 3, 0),
        "sv": "F3",
        "ml": 9,
        "tt": "B",
        "dungeonlevel": 4),
    },
    "Caecilia, Giant": {
        "name": "Caecilia, Giant",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (6, 8, 0),
        "noatt": "1 bite + swallow on 19/20",
        "dam": "1d8 + 1d8/round if swallowed",
        "mv": "20' (10')",
        "noapp": (1, 3, 0),
        "sv": "F3",
        "ml": 9,
        "tt": "B",
        "dungeonlevel": 6),
    },
    "Carnivorous Ape": {
        "name": "Carnivorous Ape",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (4, 8, 0),
        "noatt": "2 claws",
        "dam": "1d4/1d4",
        "mv": "40'",
        "noapp": (1, 6, 0),
        "sv": "F4",
        "ml": 7,
        "tt": "None",
        "dungeonlevel": 3),
    },
    "Chimera": {
        "name": "Chimera",
        "ac": 16,
        "daggers": 0,
        "asterisk": 0,
        "hd": (9, 8, 0),
        "noatt": "2 claws/3 heads + special",
        "dam": "1d4/1d4/2d4/2d4/3d4 + special",
        "mv": "40' (10') Fly 60' (15')",
        "noapp": (1, 2, 0),
        "sv": "F9",
        "ml": 9,
        "tt": "F",
        "dungeonlevel": 8),
    },
    "Cockatrice": {
        "name": "Cockatrice",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (5, 8, 0),
        "noatt": "1 beak + special",
        "dam": "1d6 + petrification",
        "mv": "30' Fly 60' (10')",
        "noapp": (1, 4, 0),
        "sv": "F5",
        "ml": 7,
        "tt": "D",
        "dungeonlevel": 4),
    },
    "Displacer": {
        "name": "Displacer",
        "ac": 16,
        "daggers": 0,
        "asterisk": 0,
        "hd": (6, 8, 0),
        "noatt": "2 blades",
        "dam": "1d8/1d8",
        "mv": "50'",
        "noapp": (1, 4, 0),
        "sv": "F6",
        "ml": 8,
        "tt": "D",
        "dungeonlevel": 6),
    },
    "Doppleganger": {
        "name": "Doppleganger",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (4, 8, 0),
        "noatt": "1",
        "dam": "1d12 or by weapon",
        "mv": "30'",
        "noapp": (1, 6, 0),
        "sv": "F4",
        "ml": 10,
        "tt": "E",
        "dungeonlevel": (3, 4)),
    },
    "Gargoyle": {
        "name": "Gargoyle",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (4, 8, 0),
        "noatt": "2 claws/1 bite/1 horn",
        "dam": "1d4/1d4/1d6/1d4",
        "mv": "30' Fly 50' (15')",
        "noapp": (1, 6, 0),
        "sv": "F6",
        "ml": 11,
        "tt": "C",
        "dungeonlevel": 3),
    },
    "Gelatinous Cube": {
        "name": "Gelatinous Cube",
        "ac": 12,
        "daggers": 0,
        "asterisk": 0,
        "hd": (4, 8, 0),
        "noatt": "1",
        "dam": "2d4 + paralysis",
        "mv": "20'",
        "noapp": (0, 0, 1),
        "sv": "F2",
        "ml": 12,
        "tt": "V",
        "dungeonlevel": 3),
    },
    "Ghoul": {
        "name": "Ghoul",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 0),
        "noatt": "2 claws/1 bite",
        "dam": "1d4/1d4/1d4, all plus paralysis",
        "mv": "30'",
        "noapp": (1, 6, 0),
        "sv": "F2",
        "ml": 9,
        "tt": "B",
        "dungeonlevel": 2),
    },
    "Giant Ant": {
        "name": "Giant Ant",
        "ac": 17,
        "daggers": 0,
        "asterisk": 0,
        "hd": (4, 8, 0),
        "noatt": "1",
        "dam": "2d6",
        "mv": "60'",
        "noapp": (2, 6, 0),
        "sv": "F4",
        "ml": 7,
        "tt": "U",
        "dungeonlevel": 3),
    },
    "Giant Bee": {
        "name": "Giant Bee",
        "ac": 13,
        "daggers": 0,
        "asterisk": 0,
        "hd": (1, 4, 0),
        "noatt": "1 sting",
        "dam": "1d4 + poison",
        "mv": "10' Fly 50'",
        "noapp": (1, 6, 0),
        "sv": "F1",
        "ml": 9,
        "tt": "Special",
        "dungeonlevel": 1),
    },
    "Giant Black Widow Spider": {
        "name": "Giant Black Widow Spider",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (3, 8, 0),
        "noatt": "1 bite",
        "dam": "2d6 + poison",
        "mv": "20' Web 40'",
        "noapp": (1, 3, 0),
        "sv": "F3",
        "ml": 8,
        "tt": "None",
        "dungeonlevel": 2),
    },
    "Giant Bombardier Beetle": {
        "name": "Giant Bombardier Beetle",
        "ac": 16,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 0),
        "noatt": "1 bite/1 spray",
        "dam": "1d6/2d6 (cone 10' wide by 10' long from rear of monster, save vs. Death Ray for half damage)",
        "mv": "40'",
        "noapp": (1, 8, 0),
        "sv": "F2",
        "ml": 8,
        "tt": "None",
        "dungeonlevel": 2),
    },
    "Giant Crab Spider": {
        "name": "Giant Crab Spider",
        "ac": 13,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 0),
        "noatt": "1 bite",
        "dam": "1d8 + poison",
        "mv": "40'",
        "noapp": (1, 4, 0),
        "sv": "F2",
        "ml": 7,
        "tt": "None",
        "dungeonlevel": 1),
    },
    "Giant Fly": {
        "name": "Giant Fly",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 0),
        "noatt": "1 bite",
        "dam": "1d8",
        "mv": "30' Fly 60'",
        "noapp": (1, 6, 0),
        "sv": "F1",
        "ml": 8,
        "tt": "None",
        "dungeonlevel": 2),
    },
    "Giant Tiger Beetle": {
        "name": "Giant Tiger Beetle",
        "ac": 17,
        "daggers": 0,
        "asterisk": 0,
        "hd": (3, 8, 1),
        "noatt": "1",
        "dam": "2d6",
        "mv": "50'",
        "noapp": (1, 6, 0),
        "sv": "F3",
        "ml": 9,
        "tt": "U",
        "dungeonlevel": 3),
    },
    "Giant, Hill": {
        "name": "Giant, Hill",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (8, 8, 0),
        "noatt": "1",
        "dam": "2d8",
        "mv": "40'",
        "noapp": (1, 4, 0),
        "sv": "F8",
        "ml": 8,
        "tt": ("E", (1, 8, 0, 1000), "GP"),
        "dungeonlevel": 8),
    },
    "Giant, Stone": {
        "name": "Giant, Stone",
        "ac": 17,
        "daggers": 0,
        "asterisk": 0,
        "hd": (9, 8, 0),
        "noatt": "1 stone club or 1 thrown rock",
        "dam": "3d6 or 3d6",
        "mv": "40'",
        "noapp": (1, 2, 0),
        "sv": "F9",
        "ml": 9,
        "tt": ("E", (1, 8, 0, 1000), "GP"),
        "dungeonlevel": 8),
    },
    "Gnoll": {
        "name": "Gnoll",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 0),
        "noatt": "1 weapon",
        "dam": "2d4 or by weapon +1",
        "mv": "30'",
        "noapp": (1, 6, 0),
        "sv": "F1",
        "ml": 8,
        "tt": ("D", "K"),
        "dungeonlevel": 2),
    },
    "Goblin": {
        "name": "Goblin",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (1, 8, -1),
        "noatt": "1 weapon",
        "dam": "1d6 or by weapon",
        "mv": "20'",
        "noapp": (2, 4, 0),
        "sv": "F1",
        "ml": 7,
        "tt": "C",
        "dungeonlevel": 1),
    },
    "Gray Ooze": {
        "name": "Gray Ooze",
        "ac": 12,
        "daggers": 0,
        "asterisk": 0,
        "hd": (3, 8, 0),
        "noatt": "1",
        "dam": "2d8",
        "mv": "1'",
        "noapp": (0, 0, 1),
        "sv": "F3",
        "ml": 12,
        "tt": "None",
        "dungeonlevel": (2, 4)),
    },
    "Green Slime": {
        "name": "Green Slime",
        "asterisk": 1,
        "ac": "can always be hit",
        "daggers": 0,
        "hd": (2, 8, 0),
        "noatt": "1",
        "dam": "special",
        "mv": "1'",
        "noapp": (0, 0, 1),
        "sv": "F2",
        "ml": 12,
        "tt": "None",
        "dungeonlevel": 1),
    },
    "Hellhound": {
        "name": "Hellhound",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (4, 8, 0),
        "noatt": "1 bite or 1 breath",
        "dam": "1d6 or 1d6 per Hit Die",
        "mv": "40'",
        "noapp": (2, 4, 0),
        "sv": "F4",
        "ml": 9,
        "tt": "C",
        "dungeonlevel": 4),
    },
    "Hobgoblin": {
        "name": "Hobgoblin",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (1, 8, 0),
        "noatt": "1 weapon",
        "dam": "1d8 or by weapon",
        "mv": "30'",
        "noapp": (1, 6, 0),
        "sv": "F1",
        "ml": 8,
        "tt": ("D", "K"),
        "dungeonlevel": 2),
    },
    "Hydra, 6 Headed": {
        "name": "Hydra, 6 Headed",
        "ac": 17,
        "daggers": 0,
        "asterisk": 0,
        "hd": (6, 8, 0),
        "noatt": "6 bites",
        "dam": "1d10 per bite",
        "mv": "40' (10')",
        "noapp": (0, 0, 1),
        "sv": "F6",
        "ml": 9,
        "tt": "B",
        "dungeonlevel": 6),
    },
    "Hydra, 7 Headed": {
        "name": "Hydra, 7 Headed",
        "ac": 18,
        "daggers": 0,
        "asterisk": 0,
        "hd": (7, 8, 0),
        "noatt": "7 bites",
        "dam": "1d10 per bite",
        "mv": "40' (10')",
        "noapp": (0, 0, 1),
        "sv": "F7",
        "ml": 9,
        "tt": "B",
        "dungeonlevel": 8),
    },
    "Kobold": {
        "name": "Kobold",
        "ac": 13,
        "daggers": 0,
        "asterisk": 0,
        "hd": (1, 4, 0),
        "noatt": "1 weapon",
        "dam": "1d4 or by weapon",
        "mv": "20'",
        "noapp": (4, 4, 0),
        "sv": "NM",
        "ml": 6,
        "tt": "C",
        "dungeonlevel": 1),
    },
    "Lizard Man": {
        "name": "Lizard Man",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 0),
        "noatt": "1 weapon",
        "dam": "1d6+1 or by weapon +1",
        "mv": "20'",
        "noapp": (2, 4, 0),
        "sv": "F2",
        "ml": 11,
        "tt": "D",
        "dungeonlevel": 2),
    },
    "Lycanthrope, Wereboar": {
        "name": "Lycanthrope, Wereboar",
        "ac": 16,
        "daggers": 0,
        "asterisk": 1,
        "hd": (4, 8, 0),
        "noatt": "1 bite",
        "dam": "2d6",
        "mv": "50' Human Form 40'",
        "noapp": (1, 4, 0),
        "sv": "F4",
        "ml": 9,
        "tt": "C",
        "dungeonlevel": 8),
    },
    "Lycanthrope, Wererat": {
        "name": "Lycanthrope, Wererat",
        "ac": 13,
        "daggers": 0,
        "asterisk": 1,
        "hd": (3, 8, 0),
        "noatt": "1 bite or 1 weapon",
        "dam": "1d4 or 1d6 or by weapon",
        "mv": "40'",
        "noapp": (1, 8, 0),
        "sv": "F3",
        "ml": 8,
        "tt": "C",
        "dungeonlevel": 3),
    },
    "Lycanthrope, Weretiger": {
        "name": "Lycanthrope, Weretiger",
        "ac": 17,
        "daggers": 0,
        "asterisk": 1,
        "hd": (5, 8, 0),
        "noatt": "2 claws/1 bite",
        "dam": "1d6/1d6/2d6",
        "mv": "50' Human Form 40'",
        "noapp": (1, 4, 0),
        "sv": "F5",
        "ml": 9,
        "tt": "C",
        "dungeonlevel": 6),
    },
    "Lycanthrope, Werewolf": {
        "name": "Lycanthrope, Werewolf",
        "ac": 15,
        "daggers": 0,
        "asterisk": 1,
        "hd": (4, 8, 0),
        "noatt": "1 bite",
        "dam": "2d4",
        "mv": "60' Human Form 40'",
        "noapp": (1, 6, 0),
        "sv": "F4",
        "ml": 8,
        "tt": "C",
        "dungeonlevel": 4),
    },
    "Minotaur": {
        "name": "Minotaur",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (6, 8, 0),
        "noatt": "1 gore/1 bite or 1 weapon",
        "dam": "1d6/1d6 or by weapon + 2",
        "mv": "40'",
        "noapp": (1, 6, 0),
        "sv": "F6",
        "ml": 11,
        "tt": "C",
        "dungeonlevel": 4),
    },
    "Mummy": {
        "name": "Mummy",
        "ac": 17,
        "daggers": 0,
        "asterisk": 1,
        "hd": (5, 8, 0),
        "noatt": "1 touch + disease",
        "dam": "1d12 + disease",
        "mv": "20'",
        "noapp": (1, 4, 0),
        "sv": "F5",
        "ml": 12,
        "tt": "D",
        "dungeonlevel": 6),
    },
    "Ochre Jelly": {
        "name": "Ochre Jelly",
        "ac": 12,
        "daggers": 0,
        "asterisk": 1,
        "hd": (5, 8, 0),
        "noatt": "1",
        "dam": "2d6",
        "mv": "10'",
        "noapp": (0, 0, 1),
        "sv": "F5",
        "ml": 12,
        "tt": "None",
        "dungeonlevel": 4),
    },
    "Ogre": {
        "name": "Ogre",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (4, 8, 1),
        "noatt": "1 weapon",
        "dam": "2d6",
        "mv": "30'",
        "noapp": (1, 6, 0),
        "sv": "F4",
        "ml": 10,
        "tt": ("C", (1, 20, 0, 100), "GP"),
        "dungeonlevel": 3),
    },
    "Orc": {
        "name": "Orc",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (1, 8, 0),
        "noatt": "1 weapon",
        "dam": "1d8 or by weapon",
        "mv": "40'",
        "noapp": (2, 4, 0),
        "sv": "F1",
        "ml": 8,
        "tt": "D",
        "dungeonlevel": 1),
    },
    "Owlbear": {
        "name": "Owlbear",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (5, 8, 0),
        "noatt": "2 claws/1 bite + 1 hug",
        "dam": "1d8/1d8/1d8 + 2d8",
        "mv": "40'",
        "noapp": (1, 4, 0),
        "sv": "F5",
        "ml": 9,
        "tt": "C",
        "dungeonlevel": (4, 6)),
    },
    "Pit Viper": {
        "name": "Pit Viper",
        "ac": 14,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 0),
        "noatt": "1 bite",
        "dam": "1d4 + poison",
        "mv": "30'",
        "noapp": (1, 8, 0),
        "sv": "F2",
        "ml": 7,
        "tt": "None",
        "dungeonlevel": 2),
    },
    "Purple Worm": {
        "name": "Purple Worm",
        "ac": 16,
        "daggers": 0,
        "asterisk": 0,
        "hd": (11, 8, 0),
        "noatt": "1 bite/1 sting",
        "dam": "2d8/1d8+poison",
        "mv": "20' (15')",
        "noapp": (1, 2, 0),
        "sv": "F6",
        "ml": 10,
        "tt": "None",
        "dungeonlevel": 8),
    },
    "Rust Monster": {
        "name": "Rust Monster",
        "ac": 18,
        "daggers": 0,
        "asterisk": 1,
        "hd": (5, 8, 0),
        "noatt": "1",
        "dam": "special",
        "mv": "40'",
        "noapp": (1, 4, 0),
        "sv": "F5",
        "ml": 7,
        "tt": "None",
        "dungeonlevel": (4, 6)),
    },
    "Salamander*, Flame": {
        "name": "Salamander*, Flame",
        "ac": 19,
        "daggers": 0,
        "asterisk": 0,
        "hd": (8, 8, 0),
        "noatt": "2 claws/1 bite+heat",
        "dam": "1d4/1d4/1d8+1d8/round",
        "mv": "40'",
        "noapp": (1, 4, 1),
        "sv": "F8",
        "ml": 8,
        "tt": "F",
        "dungeonlevel": 8),
    },
    "Salamander*, Frost": {
        "name": "Salamander*, Frost",
        "ac": 21,
        "daggers": 0,
        "asterisk": 0,
        "hd": (12, 8, 0),
        "noatt": "4 claws/1 bite+cold",
        "dam": "1d6/1d6/1d6/1d6/2d6+1d8/round",
        "mv": "40'",
        "noapp": (1, 3, 0),
        "sv": "F12",
        "ml": 9,
        "tt": "E",
        "dungeonlevel": 8),
    },
    "Scorpion, Giant": {
        "name": "Scorpion, Giant",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (4, 8, 0),
        "noatt": "2 claws/1 stinger",
        "dam": "1d10/1d10/1d6 + poison",
        "mv": "50' (10')",
        "noapp": (1, 6, 0),
        "sv": "F2",
        "ml": 11,
        "tt": "None",
        "dungeonlevel": 6),
    },
    "Shadow": {
        "name": "Shadow",
        "ac": 13,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 0),
        "noatt": "1 touch",
        "dam": "1d4 + 1 point Strength loss",
        "mv": "30'",
        "noapp": (1, 10, 0),
        "sv": "F2",
        "ml": 12,
        "tt": "F",
        "dungeonlevel": 3),
    },
    "Skeleton": {
        "name": "Skeleton",
        "ac": 13,
        "daggers": 0,
        "asterisk": 0,
        "hd": (1, 8, 0),
        "noatt": "1",
        "dam": "1d6 or by weapon",
        "mv": "40'",
        "noapp": (3, 4, 0),
        "sv": "F1",
        "ml": 12,
        "tt": "None",
        "dungeonlevel": 1),
    },
    "Spectre": {
        "name": "Spectre",
        "ac": 17,
        "daggers": 0,
        "asterisk": 1,
        "hd": (6, 8, 0),
        "noatt": "1 touch",
        "dam": "Energy drain 2 levels/touch",
        "mv": "Fly 100'",
        "noapp": (1, 4, 0),
        "sv": "F6",
        "ml": 11,
        "tt": "E",
        "dungeonlevel": 6),
    },
    "Spitting Cobra": {
        "name": "Spitting Cobra",
        "ac": 13,
        "daggers": 0,
        "asterisk": 0,
        "hd": (1, 8, 0),
        "noatt": "1 bite or 1 spit",
        "dam": "1d4 + poison or blindness",
        "mv": "30'",
        "noapp": (1, 6, 0),
        "sv": "F1",
        "ml": 7,
        "tt": "None",
        "dungeonlevel": 1),
    },
    "Stirge": {
        "name": "Stirge",
        "ac": 13,
        "daggers": 0,
        "asterisk": 0,
        "hd": (1, 8, 0),
        "noatt": "1 bite",
        "dam": "1d4 + 1d4/round blood drain",
        "mv": "10' Fly 60'",
        "noapp": (1, 10, 0),
        "sv": "F1",
        "ml": 9,
        "tt": "D",
        "dungeonlevel": 1),
    },
    "Tentacle Worm": {
        "name": "Tentacle Worm",
        "ac": 13,
        "daggers": 0,
        "asterisk": 0,
        "hd": (3, 8, 0),
        "noatt": "6 tentacles",
        "dam": "paralysis",
        "mv": "40'",
        "noapp": (1, 3, 0),
        "sv": "F3",
        "ml": 9,
        "tt": "B",
        "dungeonlevel": 3),
    },
    "Troglodyte": {
        "name": "Troglodyte",
        "ac": 15,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 0),
        "noatt": "2 claws/1 bite",
        "dam": "1d4/1d4/1d4",
        "mv": "40'",
        "noapp": (1, 8, 0),
        "sv": "F2",
        "ml": 9,
        "tt": "A",
        "dungeonlevel": 2),
    },
    "Troll": {
        "name": "Troll",
        "ac": 16,
        "daggers": 0,
        "asterisk": 0,
        "hd": (6, 8, 0),
        "noatt": "3",
        "dam": "1d6/1d6/1d10",
        "mv": "40'",
        "noapp": (1, 8, 0),
        "sv": "F6",
        "ml": 10,
        "tt": "D",
        "dungeonlevel": 6),
    },
    "Vampire": {
        "name": "Vampire",
        "ac": 18,
        "daggers": 0,
        "asterisk": 1,
        "hd": (7, 8, 0),
        "noatt": "1 weapon or special",
        "dam": "1d8 or by weapon or special",
        "mv": "40' Fly 60'",
        "noapp": (1, 6, 0),
        "sv": "F7",
        "ml": 11,
        "tt": "F",
        "dungeonlevel": 8),
    },
    "Wight": {
        "name": "Wight",
        "ac": 15,
        "daggers": 0,
        "asterisk": 1,
        "hd": (3, 8, 0),
        "noatt": "1 touch",
        "dam": "Energy drain (1 level)",
        "mv": "30'",
        "noapp": (1, 6, 0),
        "sv": "F3",
        "ml": 12,
        "tt": "B",
        "dungeonlevel": 3),
    },
    "Wolf": {
        "name": "Wolf",
        "ac": 13,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 0),
        "noatt": "1 bite",
        "dam": "1d6",
        "mv": "60'",
        "noapp": (2, 6, 0),
        "sv": "F2",
        "ml": 8,
        "tt": "None",
        "dungeonlevel": 1),
    },
    "Wraith": {
        "name": "Wraith",
        "ac": 15,
        "daggers": 0,
        "asterisk": 1,
        "hd": (4, 8, 0),
        "noatt": "1 touch",
        "dam": "1d6 + energy drain (1 level)",
        "mv": "Fly 80'",
        "noapp": (1, 4, 0),
        "sv": "F4",
        "ml": 12,
        "tt": "E",
        "dungeonlevel": 4),
    },
    "Zombie": {
        "name": "Zombie",
        "ac": 12,
        "daggers": 0,
        "asterisk": 0,
        "hd": (2, 8, 0),
        "noatt": "1",
        "dam": "1d8 or by weapon",
        "mv": "20'",
        "noapp": (2, 4, 0),
        "sv": "F2",
        "ml": 12,
        "tt": "None",
        "dungeonlevel": 2),
    },
}

# end of file.
